# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for OSINT Investigation Suite."""

import sys
from pathlib import Path

block_cipher = None
base_dir = Path('.')
src_dir = base_dir / 'src'
web_dir = src_dir / 'osintsuite' / 'web'

a = Analysis(
    ['launcher.py'],
    pathex=[str(src_dir)],
    binaries=[],
    datas=[
        (str(web_dir / 'templates'), 'osintsuite/web/templates'),
        (str(web_dir / 'static'), 'osintsuite/web/static'),
    ],
    hiddenimports=[
        'osintsuite',
        'osintsuite.web',
        'osintsuite.web.app',
        'osintsuite.web.routers',
        'osintsuite.web.routers.dashboard',
        'osintsuite.web.routers.investigations',
        'osintsuite.web.routers.targets',
        'osintsuite.web.routers.findings',
        'osintsuite.web.routers.reports',
        'osintsuite.config',
        'osintsuite.db',
        'osintsuite.db.models',
        'osintsuite.db.repository',
        'osintsuite.db.session',
        'osintsuite.engine',
        'osintsuite.engine.investigation',
        'osintsuite.modules',
        'osintsuite.modules.base',
        'osintsuite.modules.person_search',
        'osintsuite.modules.email_intel',
        'osintsuite.modules.phone_lookup',
        'osintsuite.modules.domain_recon',
        'osintsuite.modules.web_scraper',
        'osintsuite.modules.social_media',
        'osintsuite.modules.ip_forensics',
        'osintsuite.modules.metadata_forensics',
        'osintsuite.modules.hash_intel',
        'osintsuite.modules.timeline_forensics',
        'osintsuite.reporting',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'starlette.responses',
        'starlette.templating',
        'pydantic',
        'pydantic_settings',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'aiosqlite',
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',
        'h11',
        'httpcore',
        'jinja2',
        'multipart',
        'email_validator',
        'dns',
        'dns.resolver',
        'phonenumbers',
        'bs4',
        'lxml',
        'lxml.html',
        'whois',
        'thefuzz',
        'rich',
        'typer',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'test', 'unittest', 'weasyprint', 'PIL'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='OSINT Suite',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

if sys.platform == 'darwin':
    app = BUNDLE(
        exe,
        name='OSINT Suite.app',
        icon=None,
        bundle_identifier='com.rmpg.osint-suite',
        info_plist={
            'CFBundleShortVersionString': '0.1.0',
            'CFBundleName': 'OSINT Suite',
            'NSHighResolutionCapable': True,
        },
    )
